# Configuration of script for visualization of graphs
#experiment_name: 'Experiment 200_TUDataset_SkipGCN'
experiment_name: 'Experiment 11'
random_state: 17

# Disable change directly and create output directories
hydra:
  job:
    chdir: False
  run:
    dir: .

# Add other config files
defaults:
  - data: config
  - training: config
  - override hydra/job_logging: custom
  # Config from this file override the values of configs from the Defaults List
  - _self_

mlflow:
  tracking_uri: 'sqlite:///${hydra:runtime.cwd}/../mlflow/mlruns.db'